from . import student_info
from . import standard_info
from . import teachers_info
from . import sports_activity
from . import library_info
from . import cultural_fest
from . import scholar_ship_info
from . import new_module_to_inherit
from . import sale_order
from . import product_module_edit
from . import weather_info
from . import inventory_info